package com.nickspeelman.localjournal.export

import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Path
import java.time.format.DateTimeFormatter
import java.util.Locale

object ChartPngRenderer {
    const val WIDTH = 1600
    const val HEIGHT = 1200
    private const val BG = 0xFFF8FAF9.toInt()
    private const val FG = 0xFF1D2925.toInt()
    private const val MUTED = 0xFF61706A.toInt()
    private const val GRID = 0xFFD9E2DE.toInt()
    private const val ACCENT = 0xFF4D8F80.toInt()

    fun render(model: ShareableChart): Bitmap {
        val bitmap = Bitmap.createBitmap(WIDTH, HEIGHT, Bitmap.Config.ARGB_8888)
        val c = Canvas(bitmap)
        c.drawColor(BG)
        val p = Paint(Paint.ANTI_ALIAS_FLAG).apply { typeface = android.graphics.Typeface.create("sans", android.graphics.Typeface.NORMAL) }
        var y = 105f
        p.color = FG; p.textSize = 60f; p.typeface = android.graphics.Typeface.DEFAULT_BOLD
        c.drawText(model.title + (model.contextLabel?.let { " · $it" } ?: ""), 110f, y, p)
        y += 72f
        p.color = MUTED; p.textSize = 34f; p.typeface = android.graphics.Typeface.DEFAULT
        val range = formatRange(model)
        c.drawText(range, 110f, y, p)
        y += 54f
        val avg = model.averageRating?.let { String.format(Locale.getDefault(), "%.1f", it) } ?: "—"
        c.drawText("${model.checkInCount} ${if (model.checkInCount == 1) "check-in" else "check-ins"} · Average $avg", 110f, y, p)

        val left = 175f; val right = 1490f; val top = 330f; val bottom = 930f
        p.strokeWidth = 2f; p.color = GRID
        for (mood in 1..5) {
            val yy = yFor(mood.toDouble(), top, bottom)
            c.drawLine(left, yy, right, yy, p)
            p.color = MUTED; p.textSize = 28f
            c.drawText(mood.toString(), 120f, yy + 10f, p)
            p.color = GRID
        }
        drawSeries(c, p, model.values, left, right, top, bottom, FG, 10f, pointsOnly = model.trendValues != null)
        model.trendValues?.let { drawSeries(c, p, it, left, right, top, bottom, ACCENT, 8f, pointsOnly = false) }
        model.comparisonTrendValues?.let { drawSeries(c, p, it, left, right, top, bottom, MUTED, 5f, pointsOnly = false, dashed = true) }

        p.color = MUTED; p.textSize = 28f
        val labels = if (model.xLabels.isEmpty()) listOf("", "", "") else model.xLabels
        labels.forEachIndexed { i, s ->
            val x = when (labels.size) { 1 -> left; else -> left + (right-left) * i / (labels.size-1).toFloat() }
            val w = p.measureText(s)
            c.drawText(s, (x - w/2).coerceIn(80f, WIDTH-80f-w), 990f, p)
        }
        p.textSize = 26f; p.color = MUTED
        val attribution = "Generated by Aside"
        c.drawText(attribution, WIDTH - 110f - p.measureText(attribution), HEIGHT - 70f, p)
        return bitmap
    }

    private fun drawSeries(c: Canvas, p: Paint, values: List<Double?>, left: Float, right: Float, top: Float, bottom: Float, color: Int, width: Float, pointsOnly: Boolean, dashed: Boolean = false) {
        if (values.isEmpty()) return
        val path = Path(); var started = false
        p.color = color; p.strokeWidth = width; p.style = Paint.Style.STROKE
        p.pathEffect = if (dashed) android.graphics.DashPathEffect(floatArrayOf(20f, 14f), 0f) else null
        values.forEachIndexed { index, value ->
            if (value == null) { if (!pointsOnly) started = false; return@forEachIndexed }
            val x = if (values.size == 1) (left+right)/2 else left + (right-left) * index/(values.size-1).toFloat()
            val y = yFor(value, top, bottom)
            if (!pointsOnly) { if (!started) { path.moveTo(x,y); started=true } else path.lineTo(x,y) }
            if (pointsOnly || values.size == 1) { p.style = Paint.Style.FILL; c.drawCircle(x,y,8f,p); p.style=Paint.Style.STROKE }
        }
        if (!pointsOnly) c.drawPath(path,p)
        p.pathEffect = null; p.style = Paint.Style.FILL
    }
    private fun yFor(v: Double, top: Float, bottom: Float): Float = bottom - (((v.coerceIn(1.0,5.0)-1.0)/4.0)*(bottom-top)).toFloat()
    private fun formatRange(model: ShareableChart): String {
        val f = DateTimeFormatter.ofPattern("MMMM d, yyyy", Locale.getDefault())
        return if (model.startDate == model.endDate) model.startDate.format(f) else "${model.startDate.format(f)} – ${model.endDate.format(f)}"
    }
}
