package com.nickspeelman.localjournal.export

import android.graphics.Color
import android.graphics.Paint
import android.graphics.Path
import android.graphics.pdf.PdfDocument
import java.io.ByteArrayOutputStream
import java.time.format.DateTimeFormatter
import java.util.Locale

object ReportPdfRenderer {
    private const val PAGE_W = 612
    private const val PAGE_H = 792
    private const val MARGIN = 52f
    private const val FG = 0xFF1D2925.toInt()
    private const val MUTED = 0xFF61706A.toInt()
    private const val GRID = 0xFFD9E2DE.toInt()
    private const val ACCENT = 0xFF4D8F80.toInt()

    fun render(report: ShareableReport): ByteArray {
        val doc = PdfDocument(); var pageNumber = 1
        val p = Paint(Paint.ANTI_ALIAS_FLAG)
        fun startPage(): Pair<PdfDocument.Page, Float> {
            val page = doc.startPage(PdfDocument.PageInfo.Builder(PAGE_W, PAGE_H, pageNumber++).create())
            page.canvas.drawColor(Color.WHITE)
            return page to MARGIN
        }
        var (page, y0) = startPage(); var y = y0
        fun finishPage() { doc.finishPage(page) }
        fun ensure(space: Float) {
            if (y + space > PAGE_H - 55f) { finishPage(); val next = startPage(); page = next.first; y = next.second }
        }
        fun text(s: String, size: Float, bold: Boolean = false, color: Int = FG, gap: Float = 8f) {
            p.color = color; p.textSize = size; p.typeface = if (bold) android.graphics.Typeface.DEFAULT_BOLD else android.graphics.Typeface.DEFAULT
            val maxWidth = PAGE_W - MARGIN*2
            val words = s.split(Regex("\\s+")); var line = ""
            val lineHeight = size * 1.32f
            for (word in words) {
                val candidate = if (line.isEmpty()) word else "$line $word"
                if (p.measureText(candidate) > maxWidth && line.isNotEmpty()) { ensure(lineHeight); page.canvas.drawText(line, MARGIN, y, p); y += lineHeight; line = word } else line = candidate
            }
            if (line.isNotEmpty()) { ensure(lineHeight); page.canvas.drawText(line, MARGIN, y, p); y += lineHeight }
            y += gap
        }

        text(report.title, 27f, true)
        val df = DateTimeFormatter.ofPattern("MMMM d, yyyy", Locale.getDefault())
        text("${report.startDate.format(df)} – ${report.endDate.format(df)}", 13f, false, MUTED, 12f)
        val avg = String.format(Locale.getDefault(), "%.1f", report.average)
        val delta = report.displayedDelta?.let { d -> when { d > 0 -> " ↑ ${String.format(Locale.getDefault(), "%.1f", kotlin.math.abs(d))}"; d < 0 -> " ↓ ${String.format(Locale.getDefault(), "%.1f", kotlin.math.abs(d))}"; else -> " → no change" } } ?: ""
        text("Average $avg$delta", 19f, true, FG, 2f)
        text("${report.checkInCount} ${if (report.checkInCount == 1) "check-in" else "check-ins"}", 12f, false, MUTED, 16f)

        ensure(220f)
        drawChart(page.canvas, report, y, 190f); y += 215f

        if (report.highest != null || report.lowest != null) {
            text("Highlights", 16f, true, FG, 4f)
            report.highest?.let { text("Highest: ${it.label} · ${String.format(Locale.getDefault(), "%.1f", it.average)}", 12f, false, FG, 1f) }
            report.lowest?.let { text("Lowest: ${it.label} · ${String.format(Locale.getDefault(), "%.1f", it.average)}", 12f, false, FG, 10f) }
        }
        if (report.timeBuckets.isNotEmpty()) {
            text("Time of day", 16f, true, FG, 3f)
            report.timeBuckets.forEach { text("${it.label} · ${String.format(Locale.getDefault(), "%.1f", it.average)} · ${it.count}", 12f, false, FG, 1f) }
            y += 8f
        }
        if (report.hashtags.isNotEmpty()) {
            text("Top hashtags", 16f, true, FG, 3f)
            report.hashtags.forEach { text("${it.tag} · ${String.format(Locale.getDefault(), "%.1f", it.average)} · ${it.count}", 12f, false, FG, 1f) }
            y += 8f
        }
        if (report.notes.isNotEmpty()) {
            ensure(80f); text("Journal notes", 18f, true, FG, 6f)
            val dtf = DateTimeFormatter.ofPattern("MMM d, yyyy · h:mm a", Locale.getDefault())
            report.notes.forEach { note ->
                ensure(70f)
                text(note.dateTime.format(dtf), 11f, true, MUTED, 0f)
                text("Rating: ${note.rating?.toString() ?: "—"}", 10f, false, MUTED, 2f)
                text(note.note, 11f, false, FG, 10f)
            }
        }
        ensure(30f); p.color = MUTED; p.textSize = 9f; p.typeface = android.graphics.Typeface.DEFAULT
        val footer = "Generated by Aside"; page.canvas.drawText(footer, PAGE_W - MARGIN - p.measureText(footer), PAGE_H - 28f, p)
        finishPage()
        val out = ByteArrayOutputStream(); doc.writeTo(out); doc.close(); return out.toByteArray()
    }

    private fun drawChart(c: android.graphics.Canvas, r: ShareableReport, top: Float, height: Float) {
        val p = Paint(Paint.ANTI_ALIAS_FLAG); val left = MARGIN+25f; val right = PAGE_W-MARGIN; val bottom = top+height
        fun yFor(v: Double) = (bottom - ((v.coerceIn(1.0,5.0)-1.0)/4.0*height)).toFloat()
        p.strokeWidth=1f; p.textSize=9f
        for (m in 1..5) { val yy=yFor(m.toDouble()); p.color=GRID; c.drawLine(left,yy,right,yy,p); p.color=MUTED; c.drawText(m.toString(), MARGIN, yy+3f,p) }
        fun series(values: List<Double?>, color: Int, width: Float, dashed: Boolean=false, points:Boolean=false) {
            val path=Path(); var started=false; p.color=color; p.strokeWidth=width; p.style=Paint.Style.STROKE; p.pathEffect=if(dashed) android.graphics.DashPathEffect(floatArrayOf(6f,5f),0f) else null
            values.forEachIndexed { i,v -> if(v==null){started=false;return@forEachIndexed}; val x=if(values.size==1)(left+right)/2 else left+(right-left)*i/(values.size-1f); val yy=yFor(v); if(points){p.style=Paint.Style.FILL;c.drawCircle(x,yy,2.8f,p);p.style=Paint.Style.STROKE}else if(!started){path.moveTo(x,yy);started=true}else path.lineTo(x,yy) }
            if(!points)c.drawPath(path,p); p.pathEffect=null; p.style=Paint.Style.FILL
        }
        series(r.dailyValues, FG, 2f, points=true); series(r.trendValues, ACCENT, 3f); r.comparisonTrendValues?.let { series(it,MUTED,1.8f,true) }
    }
}
